### ISSUE TITLE
It's possible to start the game without placing all the ships

### ISSUE THREAD

**Issue by Sokom141** [Sokom141/BattleShip#8]
This bug is easily reproducible by placing all but one ship and the activating the MouseListener without placing the last one.

The culprit is the cose inside [**ShipPlanner**  line 159](https://github.com/Sokom141/BattleShip/blob/49a919c3ccd54acc8b302cb1fa7d6b7500a983e0/src/com/battleship/GUI/ShipPlanner.java#L159) :
`if (comboBoxItemCount == 1) {
                                buttonOk.setEnabled(true);
                            }`

**Comment by sstanham** [comment]
This sounds like a very fun project, I would like to help you with your bug and maybe some of your enhancements. Can you assign this to me?

**Comment by Sokom141** [comment]
@sstanham Hi!
We are glad you want to contribute to this project.
I'm going to assign you this issue, let me know if you need anything, have fun.

**Comment by sstanham** [comment]
Thank you! I'm going through the code to get it running first. Just to make sure, where do I run the project from? I assume its the Application.java file?

**Comment by Sokom141** [comment]
> I assume its the Application.java file?

Exactly, that's the entry point of the program.

Currently I'm working on integrating Maven, for an easier and IDE-independent approach, so the project structure will change if everything works correctly.😄

**Comment by sstanham** [comment]
Hi, I'm trying to run the project from the Application.java file and I keep running into this error:

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "javax.swing.JButton.addActionListener(java.awt.event.ActionListener)" because "this.b_exit" is null
        at com.battleship.GUI.Window.initUI(Window.java:48)
        at com.battleship.GUI.Window.<init>(Window.java:36)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at `java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

Is there a dependency that I may be missing, or something else I'm missing? My IDE is VScode, if that makes a difference.

**Comment by Sokom141** [comment]
Yeah, I know about this problem, sorry about that.
I'm currently working on a fix by integrating Maven as I said above.
The culprit is that we used IntelliJ GUI builder for the .form files and it's currently creating binary files instead of Java sources.
As a immediate workaround you can use IntelliJ as your IDE or wait for the fix ( should be fast, at maximum a couple days hopefully)
Let me know

**Comment by sstanham** [comment]
Will do, I'll give IntelliJ a shot and keep you updated. Thank you!

**Comment by sstanham** [comment]
Sorry for the additional questions, but I was wondering if there was a way to playtest a game in IntelliJ. I've gotten the project downloaded and set-up, I just wanted to see how the project currently comes together.

**Comment by Sokom141** [comment]
Don't worry! 
As of now you should set your source and resources directories by going to:
File > Project Structure > Modules > BattleShip  and then marking the right directories 
src -> "Sources"
resources -> Resources
Then you should go to "Run/Debug Configurations" ( you can find it in the top right corner just next to the run button) and set 
com.battleship.Application as your main-class and setting the JRE at least to the 14 version.

Let me know if this is enough to start the project.
Right now I think my experimental maven set-up it's working so I might push an experimental branch soon.

P.S:
You can even go to the [releases](https://github.com/Sokom141/BattleShip/releases) and download the latest snapshot.
The jar also requires at least the jdk 14 for now and be aware of some [bugs](https://github.com/Sokom141/BattleShip/issues) if you trying to play

**Comment by sstanham** [comment]
Perfect, got it all up and running now. Thank you for the guide, I was unfamiliar with the IntelliJ environment.

**Comment by Sokom141** [comment]
Wonderful!
If you want to check it out I've also pushed the experimental branch with maven.
That should be IDE-independent and should also be more straightforward to import the project and run it right away 😁

**Comment by Sokom141** [comment]
Hi @sstanham !
Do you still plan to work on this issue?
We made a lot of changes, so let me know if you need something.

**Comment by sstanham** [comment]
Ah yes, sorry for not updating you on my progress, school work has been picking up. I wish to keep on this issue and will work on it as soon as I can. I'll make sure to grab the most recent branch when I get back to work on it.

**Comment by Sokom141** [comment]
> school work has been picking up. 

I feel you 😅

Don't worry and take your time, I was just checking since we got reached by new people.
If you need help hit me up!

**Comment by sstanham** [comment]
My plan is to work on this tomorrow, but I have done plenty of investigating and I believe I know how to fix this. I'll keep you posted

**Comment by Sokom141** [comment]
Good!
If you've not already I suggest to look into the contributing file (currently on the `develop` branch), it may clear some common question for you, if you need it, and help you integrate the contributions better.
Good luck and thank you for your interest

**Comment by sstanham** [comment]
I found a way to fix the bug, just let me download the most recent version of the code, I'll modify it and send a push with an explanation

**Comment by sstanham** [comment]
#34 Just sent the pull request. I wrote the reasoning there. In short, I added an extra check for a click position, to check if it's valid. That way, if you click an invalid place as the last placement, it won't count it. Let me know what you think!

**Comment by Sokom141** [comment]
Good, thank you!
I've made a comment on your pull request let me know if everything it's okay

**Comment by sstanham** [comment]
Ah perfect, I completely forgot to look for the conventions. I'll conform my changes when I return to my computer and I'll resend the request asap

**Comment by Sokom141** [comment]
Thank you for the help!

**Comment by sstanham** [comment]
Thank you! Its a very fun project, so I'll take a look at the other bugs in the issue list and see if I can fix those too

**Comment by sstanham** [comment]
I just closed the request and submitted an updated version. Please let me know if I got the formatting right, and thank you for being patient with me!

Edit: Sorry for spamming the pull requests, the last one should be the best one.
